version: '3.8'

services:
  mysql:
    image: mysql:8.0.36
    container_name: coffee_mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: coffee_management
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: coffee_management_img
    container_name: coffee_spring_app
    ports:
      - "8080:8080"
    depends_on:
      - mysql
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/coffee_management
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root

volumes:
  mysql_data:
